### ISSUE TITLE
Issue #0 - Wiki Home Page

### ISSUE THREAD

**Issue by keginzburg** [dtannyc1/Davescord#1]
# Wiki Home Page
- [X] Is the first page you see upon entering the wiki
- [ ] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [X] All links in the right sidebar should contain each wiki page and link to the correct page
- [X] Correctly formatted
  - [X] each wiki page is listed in bullet points
  - [X] all links route the correct page

## Comments

- [ ] Really nice work here, David. Small fixes, but I would make sure to include a small welcome message explaining what the Wiki is for and your app's pitch. I would also be sure to add a Live Link placeholder for when we do host our site on Render.
- **Otherwise, great work!**

**Comment by dtannyc1** [comment]
- Added placeholder link for the live page 
- Added a small description of the project to the wiki
