### ISSUE TITLE
Issue #1 - Feature List

### ISSUE THREAD

**Issue by keginzburg** [dtannyc1/Davescord#2]
# Feature List
- [X] Should have 7 MVPs.
  - [X] 3 of those are User Auth, Render, and Production README.
  - [X] The other 4 are from the [Approved Apps List](https://github.com/appacademy/cohort-resources/blob/master/full_stack_projects/aa_approved_full_stack_projects.md) or your PM will have clarified them with you
- [ ] Contains a description sentence of the app
- [X] Includes two to three detailed bullets on functionality and presentation of feature
- [X] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [X] Estimates how long it will take the code each MVP
- [X] Correctly formatted
  - [X] MVPs are listed in an ordered list
  - [X] Each MVP is broken down into bullet points

## Comments

- **This looks like a great game plan. Just a few notes.**
 - [ ] I think setting up Server Creation, Channel Creation, Live Messaging in Channels via Websockets, and Search/Friending as your core 4 features is great. Your additon of Category Creation might require another full cycle of CRUD though, so that may qualify as a 5th core feature. We can always set that as a Bonus if we want.
- [ ] Hosting on Render should take 0.5 days.
- [ ] I would make sure to designate explicit CRUD labels on your features that are full CRUD.
- [ ] Try to add a small descriptive sentence above your Features for your clone.
- **Otherwise, awesome work!**

**Comment by dtannyc1** [comment]
- Changed hosting on Render to 0.5 days
- Added CRUD labels to the main features
- Added a small sentence above the features 
- Removed category creation entirely (that information can just be stored in the channels table anyway)
