### ISSUE TITLE
Issue #2 - Database Schema

### ISSUE THREAD

**Issue by keginzburg** [dtannyc1/Davescord#3]
# Database Schema
- [X] Contains correct datatypes
- [X] Contains appropriate constraints/details
  - [X] primary key
  - [X] not null
  - [X] unique
  - [X] indexed
  - [X] foreign key
- [X] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [X] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [X] Correctly formatted
  - [X] schema is written in a table format
  - [X] the table's name are lowercased, snake_cased and `back_ticked`
  - [X] the table header column names are bolded
  - [X] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

- **This is a pretty robust database schema. You've clearly taken some time to think this over.**
- [ ] One note I have is regarding your Category table. Again, your Categories might fit as a Bonus since it's another full resource between your Servers and Channels. Is it completely necessary, or can we make our Server's work with just Channels that hold a `server_id`. Just like the JSP, I'd like for us to keep a realistic scope since web sockets might take some time to work out.
- [ ] Should your `subscriptions` table have a unique composite index between `subscriber` and `server`?
- [ ] Will your servers and channels need any additional information besides their `names`? At first glance, seems like they could hold more columns.
- **Let me know if you'd like to talk over this schema high level.**

**Comment by dtannyc1** [comment]
- `Categories` table is now removed. Instead, the `channels` table holds the `category_name` 
- Added the composite index for `subscriber` and `server` on the `subscriptions` table 
- Added a `server_image` to the `servers` table and a `description` to the `channels` table

One thing I'm not sure about is how to actually store the order in which the channels appear on the channels index. I can just sort them by id for now but I'd like the option to reorder them if I wanted to. Would it make sense to store that as another column? It seems like I'd be changing the database a lot if I just move one channel to a different place on the list.
