### ISSUE TITLE
Issue #3 - Sample State

### ISSUE THREAD

**Issue by keginzburg** [dtannyc1/Davescord#4]
# Sample State
- [X] State shape is flat!
- [X] State's keys are camelCased
- [X] All keys within the values in the state are accessible in the schema
- [X] Correctly formatted
  - [X] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [X] Top level slices
    - [X] `entities`
    - [X] `session`
    - [X] `errors` (here or in `ui`)
    - [X] `ui` (if needed)
  - [X] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can't change
    + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

- **Solid sample state.**
- [ ] Your errors slice is empty as of now, and that's okay, but you should brainstorm how errors might get populated there. Additionally, will you keep errors organized in different sub slices depending on where they render?
- [ ] Friends slice is also empty, so try to fill that in when you get a chance.
- **Great job!**

**Comment by dtannyc1** [comment]
- Added an errors slice, I'll use ids instead of sub slices to know where to render them
- Added a friends slice even though Luke and Vader aren't actually friends
