### ISSUE TITLE
Issue #4 - Backend Routes

### ISSUE THREAD

**Issue by keginzburg** [dtannyc1/Davescord#5]
# Backend Routes
- [X] Contains the following sections: HTML, API Endpoints(Backend)
- [X] Each route has a description
- [X] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
- **This doc is pretty thorough.**
- [ ] Will we need a `PATCH` and `DELETE` route for `Users`.  That is definitely solid functionality, but is it covered in our Feature List. If it's another Bonus, we can keep these for now.
- [ ] Again, I recommend we scale down and avoid Categories for now. They're not absolutely necessary and could be refactored into our Schema as a Bonus later on.
- [ ] Under `Messages` and `Private Messages`,  we have a lot of route nesting going on. Is this necessary at this point. When we pull a `Channel` or a `Private Chat`, what's to stop us from also pulling all of the associated `Messages` and `Private Messages`?
- [ ] Additionally, we have nested back routes for a lot of our member routes, like `PATCH /api/channels/:channelId/messages/:messageId`. Do we need the `:channelId` when we're updating a message, or can we just use that message's unique `:messageId` to locate it and update it?
- **Let's revisit this doc tonight.**

**Comment by dtannyc1** [comment]
- Changed the routes to shallow nesting for `messages` and `private_messages`. I still want some nesting just to make grabbing all of the messages for a channel or a private chat as straightforward as possible.
- `Categories` routes were removed to reflect the removal of the table
- Removed `PATCH` and `DELETE` routes for `Users` for now, it is unnecessary

P.S. the link to the superfluous routes didn't work for me, I think that repo might be private
